//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFHE.Survey.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespondentInfo
    {
        public int RespondentId { get; set; }
        public string RespondentName { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string EduBackground { get; set; }
        public string Occupation { get; set; }
        public string Location { get; set; }
        public string MaritalStatus { get; set; }
        public string Referrer { get; set; }
        public string Suggestion { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Deleted { get; set; }
        public string Remark { get; set; }
    }
}
