//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFHE.Survey.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=SurveyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OptionInfo> OptionInfo { get; set; }
        public DbSet<QuestionInfo> QuestionInfo { get; set; }
        public DbSet<RespondentInfo> RespondentInfo { get; set; }
        public DbSet<SurveyInfo> SurveyInfo { get; set; }
        public DbSet<SurveyResult> SurveyResult { get; set; }
        public DbSet<TemplateInfo> TemplateInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
