//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFHE.Survey.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=SurveyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OptionInfo> OptionInfoes { get; set; }
        public DbSet<QuestionInfo> QuestionInfoes { get; set; }
        public DbSet<RespondentInfo> RespondentInfoes { get; set; }
        public DbSet<SurveyInfo> SurveyInfoes { get; set; }
        public DbSet<SurveyResult> SurveyResults { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
    }
}
