//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFHE.Survey.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResult
    {
        public int SurveyResultId { get; set; }
        public int SurveyId { get; set; }
        public int RespondentId { get; set; }
        public int QuestionId { get; set; }
        public string SelectedOptions { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
